name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Install deps
      run: npm install

    - name: Run tests
      run: npm run test
    
    - name: Build React App
      run: CI=false npm run build # CI=false to ignore warnings
        
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to Surge
      run:  surge ./build https://pomodor.surge.sh/ --token ${{secrets.TOKEN}}
